<?php

/**
 * @file
 * Contains module file for starrating.
 */

/**
 * Impements hook_theme.
 */
function custom_starating_theme($existing, $type, $theme, $path) {
  return [
    'custom_starating_formatter' => [
      'variables' => [
        'rate' => 6,
        'min' => NULL,
        'max' => NULL,
        'icon_type' => NULL,
        'icon_color' => NULL,
        'fill_blank' => NULL,
        'type' => 'custom_starating',
      ],
    ],
  ];
}
